// This PAWN script is generated by WOWCube SDK project wizard

forward run(const pkt[], size, const src[]); // public Pawn function seen from C

// Includes
// -----------------------------

#include "cubios_abi.pwn"
#include "trbl.pwn"
#include "math.pwn"
#include "run.pwn"

// WOWCube application callbacks 
// -----------------------------

//Applicaton initialization callback. Called once when CUB application starts
ON_INIT()
{
}

//Main run loop callback. Gets called recurrently by the CUB application as frequent as application code allows. 
ONTICK()
{
}

//The "physics" callback. Gets called recurrently with 30ms resolution. 
ON_PHYSICS_TICK() 
{
}

//The "inner network" callback. Gets called when WOWCube module receives a data packet from other module
ON_CMD_NET_RX(const pkt[])
{
}

ON_LOAD_GAME_DATA()
{
}

//The cube topology change callback. Gets called when cube is twisted and its topological desctiption has been changed
ON_CHECK_ROTATE() 
{
} 

//This callback is obsolete and left here for compatibility purposes only. Do not use it.
RENDER(){}

#ifdef CUBIOS_EMULATOR
main()
{
new opt{ 100 }
argindex(0, opt);
abi_cubeN = strval(opt);
printf("Cube %d logic. Listening on port: %d\n", abi_cubeN, (PAWN_PORT_BASE + abi_cubeN));
listenport(PAWN_PORT_BASE + abi_cubeN);
}
#endif
