// This PAWN script is generated by WOWCube SDK project wizard

forward run(const pkt[], size, const src[]); // public Pawn function seen from C

// Includes
// -----------------------------

#include "cubios_abi.inc"
#include "trbl.inc"
#include "math.inc"
#include "run.inc"

// Application defines
// -----------------------------
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240

#define TEXT_SIZE       8

// Application variables
// -----------------------------
new theImageHandle = 0;

// WOWCube application callbacks 
// -----------------------------

//Applicaton initialization callback. Called once when CUB application starts
ON_INIT()
{
    #ifndef CUBIOS_EMULATOR
        theImageHandle = getSpriteIdByName("cube.png");
    #endif
}

//Main run loop callback. Gets called recurrently by the CUB application as frequent as application code allows. 
ONTICK()
{
    // detect device shake and quit application
    // pay attention: 
    //  detecting shakes of each module of a cube is redundant and should not be done; it is enough to choose a single module and continuously perform recurrent checks 
    if (0 == abi_cubeN) 
        {
            abi_checkShake();
        }
}

//This callback is gets called immediately after ONTICK(). Use it for calling your rendering code. 
RENDER()
{ 
    //fill the first screen of each module with black
    abi_CMD_FILL(0,0,0);
    //draw bitmap at the center of a screen
    abi_CMD_BITMAP(theImageHandle, 120, 120, 0, MIRROR_BLANK);

    //commit to screen buffer
    abi_CMD_REDRAW(0);
            
            
    //fill the second screen of each module with black
    abi_CMD_FILL(0,0,0);
    //draw bitmap at the center of a screen
    abi_CMD_BITMAP(theImageHandle, 120, 120, 0, MIRROR_BLANK);

    //commit to screen buffer
    abi_CMD_REDRAW(1);


    //fill the third screen of each module with black
    abi_CMD_FILL(0,0,0);
    //draw bitmap at the center of a screen
    abi_CMD_BITMAP(theImageHandle, 120, 120, 0, MIRROR_BLANK);

    //commit to screen buffer
    abi_CMD_REDRAW(2);
}

//The "physics" callback. Gets called recurrently with 30ms resolution. 
ON_PHYSICS_TICK() 
{
}

//The "inner network" callback. Gets called when WOWCube module receives a data packet from other module
ON_CMD_NET_RX(const pkt[])
{
}

ON_LOAD_GAME_DATA()
{
}

//The cube topology change callback. Gets called when cube is twisted and its topological desctiption has been changed
ON_CHECK_ROTATE() 
{
} 


// User-defined functions
// -----------------------------